import { describe, it, expect } from 'vitest';
import { metadata } from '../app/config';

describe('metadata', () => {
  it('correct title', () => {
    expect(metadata.title).toBe('Create Next App RaM');
  });

  it('correct description', () => {
    expect(metadata.description).toBe('Generated by create next app');
  });
});
