import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ErrorBoundary from '../components/bundler/Bundler';
import SearchComponent from '../components/serachContainer/SearhContainer';
import ThemeWrapper from '../components/themedWrapper/ThemedWrapper';
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorBoundary hasError={false} errorMessage={'Error on this page'}>
        <ThemeWrapper>
          <div>
            <h1 className={styles['main-title']}>Rick and Morty</h1>
            <SearchComponent />
          </div>
        </ThemeWrapper>
      </ErrorBoundary>
    </>
  );
}
